"""Stereo rig configuration: measure it once, load it everywhere.

Writes three files:

``stereo_config.yaml``
    Our own schema, in ROS 2 parameter layout (``/**: ros__parameters:``) so a
    node can load it directly with ``--params-file``. This is what
    ``stereo_vision.py`` reads.

``left.yaml`` / ``right.yaml``
    Standard ``sensor_msgs/CameraInfo`` files in the layout
    ``camera_info_manager`` expects, so the stock ROS 2 image pipeline
    (``stereo_image_proc`` and friends) can consume the same rig.

The right camera's projection matrix carries ``Tx = -fx * baseline``, which is
how ROS encodes the baseline for a rectified stereo pair.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, asdict, field
from pathlib import Path
from typing import Any

import yaml

from .cameras import CameraSpec, get_camera

__all__ = ["CameraConfig", "StereoConfig", "load_config"]

SCHEMA_VERSION = 1


@dataclass
class CameraConfig:
    """One eye of the rig."""

    port: str
    camera_key: str
    serial_number: str | None = None
    focal_px: float | None = None          # None -> derive from the spec
    image_width: int = 240
    image_height: int = 240

    @property
    def spec(self) -> CameraSpec:
        return get_camera(self.camera_key)

    def resolved_focal_px(self) -> float:
        """Measured focal length if we have one, otherwise the nominal one."""
        if self.focal_px:
            return float(self.focal_px)
        return self.spec.focal_px(self.image_width)

    @property
    def principal_point(self) -> tuple[float, float]:
        return self.image_width / 2.0, self.image_height / 2.0


@dataclass
class StereoConfig:
    """A stereo pair: two cameras, a baseline, and how they are aimed."""

    left: CameraConfig
    right: CameraConfig
    baseline_m: float
    convergence_deg: float = 0.0
    #: How far apart two frames may be timestamped and still count as a pair.
    max_sync_skew_ms: float = 60.0
    #: Assumed real-world height of the tracked object, for the per-camera
    #: (monocular) distance readout only. Stereo depth does not use it.
    object_height_m: float = 0.20
    notes: str = ""

    # -- geometry -----------------------------------------------------------

    def __post_init__(self) -> None:
        if self.baseline_m <= 0:
            raise ValueError("baseline_m must be positive")
        if not -60.0 <= self.convergence_deg <= 60.0:
            raise ValueError("convergence_deg outside a plausible range")

    @property
    def is_parallel(self) -> bool:
        """Parallel rigs get the simple Z = f*B/d relation; converged do not."""
        return abs(self.convergence_deg) < 0.1

    def min_measurable_distance_m(self, max_disparity_px: float | None = None) -> float:
        """Closest range the rig can resolve, set by the widest disparity."""
        limit = max_disparity_px or self.left.image_width
        return self.left.resolved_focal_px() * self.baseline_m / limit

    def max_measurable_distance_m(self, min_disparity_px: float = 1.0) -> float:
        """Range at which one pixel of disparity is all that is left."""
        return self.left.resolved_focal_px() * self.baseline_m / min_disparity_px

    # -- serialisation ------------------------------------------------------

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_version": SCHEMA_VERSION,
            "baseline_m": round(self.baseline_m, 6),
            "convergence_deg": round(self.convergence_deg, 4),
            "max_sync_skew_ms": self.max_sync_skew_ms,
            "object_height_m": self.object_height_m,
            "notes": self.notes,
            "left": asdict(self.left),
            "right": asdict(self.right),
        }

    def save(self, path: Path) -> None:
        """Write the rig config in ROS 2 parameter layout."""
        payload = {"/**": {"ros__parameters": self.to_dict()}}
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("w", encoding="utf-8") as handle:
            handle.write(
                "# Stereo rig configuration - generated by calibrate_stereo.py\n"
                "# Load in ROS 2 with:  --params-file <this file>\n"
            )
            yaml.safe_dump(payload, handle, sort_keys=False, default_flow_style=False)

    # -- ROS 2 CameraInfo ---------------------------------------------------

    def _camera_info(self, side: str) -> dict[str, Any]:
        camera = self.left if side == "left" else self.right
        fx = fy = camera.resolved_focal_px()
        cx, cy = camera.principal_point

        # Tx encodes the baseline for the right camera of a rectified pair.
        tx = 0.0 if side == "left" else -fx * self.baseline_m

        return {
            "image_width": camera.image_width,
            "image_height": camera.image_height,
            "camera_name": side,
            "camera_matrix": {
                "rows": 3, "cols": 3,
                "data": [fx, 0.0, cx, 0.0, fy, cy, 0.0, 0.0, 1.0],
            },
            # Zero until a real checkerboard calibration is run. A fisheye lens
            # genuinely needs this filled in; see the README.
            "distortion_model": "plumb_bob",
            "distortion_coefficients": {
                "rows": 1, "cols": 5, "data": [0.0, 0.0, 0.0, 0.0, 0.0],
            },
            "rectification_matrix": {
                "rows": 3, "cols": 3,
                "data": [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0],
            },
            "projection_matrix": {
                "rows": 3, "cols": 4,
                "data": [fx, 0.0, cx, tx, 0.0, fy, cy, 0.0, 0.0, 0.0, 1.0, 0.0],
            },
        }

    def save_camera_info(self, directory: Path) -> list[Path]:
        """Write left.yaml and right.yaml for the ROS 2 image pipeline."""
        directory.mkdir(parents=True, exist_ok=True)
        written = []
        for side in ("left", "right"):
            path = directory / f"{side}.yaml"
            with path.open("w", encoding="utf-8") as handle:
                handle.write(
                    f"# sensor_msgs/CameraInfo for the {side} camera\n"
                    "# Generated by calibrate_stereo.py. Distortion is all\n"
                    "# zeros until a checkerboard calibration is run.\n"
                )
                yaml.safe_dump(self._camera_info(side), handle,
                               sort_keys=False, default_flow_style=False)
            written.append(path)
        return written


def load_config(path: Path) -> StereoConfig:
    """Read a config written by :meth:`StereoConfig.save`."""
    with Path(path).open(encoding="utf-8") as handle:
        raw = yaml.safe_load(handle)

    if not isinstance(raw, dict):
        raise ValueError(f"{path} is not a YAML mapping")

    # Unwrap the ROS 2 parameter layout if present.
    for key in ("/**", "/*"):
        if key in raw:
            raw = raw[key]
            break
    raw = raw.get("ros__parameters", raw)

    version = raw.get("schema_version", SCHEMA_VERSION)
    if version != SCHEMA_VERSION:
        raise ValueError(
            f"{path} uses schema version {version}, this build expects "
            f"{SCHEMA_VERSION}. Re-run calibrate_stereo.py."
        )

    missing = [k for k in ("left", "right", "baseline_m") if k not in raw]
    if missing:
        raise ValueError(f"{path} is missing: {', '.join(missing)}")

    return StereoConfig(
        left=CameraConfig(**raw["left"]),
        right=CameraConfig(**raw["right"]),
        baseline_m=float(raw["baseline_m"]),
        convergence_deg=float(raw.get("convergence_deg", 0.0)),
        max_sync_skew_ms=float(raw.get("max_sync_skew_ms", 60.0)),
        object_height_m=float(raw.get("object_height_m", 0.20)),
        notes=str(raw.get("notes", "")),
    )
