[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#1ab176cd4d4edd38a156e0c25e12e86ad96b21ef
board = pico
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200

lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio

board_microros_distro = jazzy
board_microros_transport = serial

build_flags =
    -D CONTROL_HZ=50
